AUTHOR = "jzupka@redhat.com (J. Zupka)"
TIME = "MEDIUM"
NAME = "Multi_host migration"
TEST_CATEGORY = "Virtualization"
TEST_CLASS = 'Multihost Migration'
TEST_TYPE = "Server"
SYNC_COUNT = 2
DOC = """
Multihost_migration tests multihost migration with different configuration.

List of test are described in /client/tests/virt/cfg/subtest.cfg.sample.

Environment for test:
Storage:
  Both quest have to have acces to same shared diskplace vhere are images of
  migrated guests placed. (NFS, ...)
Network client hosts:
  Both machine on which are migration tests started have to be in same network.
Netowrk client guests:
  For some test are necessary join guest to same network. (bridge connected
  directly to network).

EXTRA_PARAMS:
  adds extra params to client part of autotest. It is possible use this Extra
  params for closer specific of running test.
  example:
  EXTRA_PARAMS = ""\"
  only pc.migrate_multi_host..ping-pong-stress.cpu_memory..tcp
  ""\"
    start migrate_multi_host only ping-pong-stress test wirh
    cpu and memory load.
"""

from autotest.server import utils

EXTRA_PARAMS = """
"""

def run(machines):
    job.run_test('multihost_migration', machines=machines,
                 extra_params=EXTRA_PARAMS, cycles=1)

if 'all' in args:
    # Run test with all machines at once.
    run(machines)
else:
    # Grab the pairs (and failures)
    (pairs, failures) = utils.form_ntuples_from_machines(machines, 2)

    # Log the failures
    for failure in failures:
        job.record("FAIL", failure[0], "kvm", failure[1])

    # Now run through each pair and run
job.parallel_simple(run, pairs, log=False)
