language: python
python:
    - "2.7"

branches:
    only:
        - master

install:
    - pip install autotest
    - pip install sphinx tox simplejson MySQL-python pylint autopep8
    - pip install inspektor
    - pip install -r requirements.txt

script:
    - inspekt lint
